
export const GET_ITEM = 'GET_ITEM'
export const GET_ITEM_ASYNC = 'GET_ITEM_ASYNC'

export const GET_ALL_ITEMS = 'GET_ALL_ITEMS'
export const GET_ALL_ITEMS_ASYNC = 'GET_ALL_ITEMS_ASYNC'

export const ADD_ITEM = 'ADD_ITEM'
export const ADD_ITEM_ASYNC = 'ADD_ITEM_ASYNC'

export const UPDATE_ITEM = 'UPDATE_ITEM'
export const UPDATE_ITEM_ASYNC = 'UPDATE_ITEM_ASYNC'

export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_ITEM_ASYNC = 'DELETE_ITEM_ASYNC'

export default {
  GET_ITEM,
  GET_ITEM_ASYNC,
  GET_ALL_ITEMS,
  GET_ALL_ITEMS_ASYNC,
  ADD_ITEM,
  ADD_ITEM_ASYNC,
  UPDATE_ITEM,
  UPDATE_ITEM_ASYNC,
  DELETE_ITEM,
  DELETE_ITEM_ASYNC
}
